"""Tests for hive_cli.services.session: stale pane-socket cleanup on start,
attach_argv()'s layout resolution (F2: renders "agent" per session), and the
F3 on-demand tabs/panes/floating-shell/control-plane-toggle functions."""

from __future__ import annotations

import contextlib
from pathlib import Path
from unittest.mock import patch

import pytest
from fakes import FakeMux

from hive_cli.config.schema import ZellijConfig
from hive_cli.config.settings import HiveSettings
from hive_cli.core import paths
from hive_cli.core.errors import HiveError
from hive_cli.git.worktree import WorktreeInfo
from hive_cli.mux.base import PaneInfo
from hive_cli.mux.tmux.backend import TmuxMux
from hive_cli.services import session
from hive_cli.state.pane_state import PaneState
from hive_cli.state.server import PaneStateServer


def _start(mux, name):
    with patch("hive_cli.services.session.os.execvpe") as execvpe:
        session.start(
            ["zellij", "attach", "--create", name],
            {},
            session=name,
            mux=mux,
            restart=False,
            restart_delay=0,
            on_restart=lambda: None,
            on_stop=lambda: None,
        )
    execvpe.assert_called_once()


def test_session_start_removes_stale_sock_dir():
    stale = paths.session_sock_dir("s")
    stale.mkdir(parents=True)
    (stale / "3.sock").write_text("")
    mux = FakeMux(session="other")  # "s" is not running

    _start(mux, "s")

    assert not stale.exists()
    assert mux.named("session_exists") == [("session_exists", ("s",), {})]


def test_session_start_keeps_live_session_dir():
    live = paths.session_sock_dir("s")
    live.mkdir(parents=True)
    (live / "3.sock").write_text("")

    _start(FakeMux(session="s"), "s")

    assert (live / "3.sock").exists()


def test_session_start_without_mux_skips_cleanup():
    stale = paths.session_sock_dir("s")
    stale.mkdir(parents=True)

    _start(None, "s")

    assert stale.exists()


def test_clean_stale_sock_dir_tolerates_missing_dir():
    session.clean_stale_sock_dir(FakeMux(session="other"), "never-created")


def test_restart_loop_sleeps_after_fast_exits():
    from hive_cli.services.restart import RestartFloor

    class Clock:
        now = 1000.0

        def __call__(self):
            return self.now

    clock = Clock()
    slept: list[float] = []
    restarts: list[int] = []
    stops: list[int] = []

    def on_restart():
        restarts.append(1)
        if len(restarts) == 2:
            raise KeyboardInterrupt

    def fake_run(cmd, env):
        clock.now += 0.1

    with patch("hive_cli.services.session.subprocess.run", side_effect=fake_run) as run:
        session.start(
            ["zellij", "attach", "--create", "s"],
            {},
            session="s",
            mux=None,
            restart=True,
            restart_delay=0,
            on_restart=on_restart,
            on_stop=lambda: stops.append(1),
            restart_floor=RestartFloor(sleep=slept.append, clock=clock),
        )

    assert run.call_count == 2
    assert slept == [1] and stops == [1]


def _settings() -> HiveSettings:
    return HiveSettings(zellij=ZellijConfig())


class TestAttachArgv:
    def test_start_renders_and_attaches(self):
        mux = FakeMux(session="s")
        cmd = session.attach_argv(
            "agent", "s", mux=mux, hive="/opt/hive", settings=_settings()
        )
        rendered = paths.layouts_dir() / "s" / "session.kdl"
        assert rendered.is_file()
        assert rendered.read_text().startswith("layout {")
        assert cmd == ["fake-attach", "s", str(rendered)]

    def test_start_legacy_layout(self):
        mux = FakeMux(session="s")
        cmd = session.attach_argv(
            "agent-16", "s", mux=mux, hive="/opt/hive", settings=_settings()
        )
        assert cmd[0] == "fake-attach"
        assert cmd[1] == "s"
        assert cmd[2].endswith("bundled/agent-16.kdl")

    def test_resolve_layout_path_none(self):
        mux = FakeMux(session="s")
        cmd = session.attach_argv(
            None, "s", mux=mux, hive="/opt/hive", settings=_settings()
        )
        assert cmd == ["fake-attach", "s", ""]


class TestPrepareTmuxAttach:
    def test_renders_conf_and_returns_attach_argv(self, fake_proc):
        mux = TmuxMux()
        cmd, ensure_session = session.prepare_tmux_attach(
            "s", mux=mux, hive="/opt/hive", settings=_settings()
        )
        del ensure_session
        conf_path = paths.layouts_dir() / "s" / "tmux.conf"
        assert conf_path.is_file()
        assert conf_path.read_text().startswith("# generated by hive")
        assert cmd == [
            "tmux",
            "-L",
            "hive",
            "-f",
            str(conf_path),
            "attach-session",
            "-t",
            "s",
        ]

    def test_ensure_session_bootstraps_when_absent(self, fake_proc):
        mux = TmuxMux()
        _cmd, ensure_session = session.prepare_tmux_attach(
            "s", mux=mux, hive="/opt/hive", settings=_settings()
        )
        conf_path = str(paths.layouts_dir() / "s" / "tmux.conf")
        fake_proc.script(
            ("tmux", "-L", "hive", "-f", conf_path, "has-session"), returncode=1
        )
        fake_proc.script(
            ("tmux", "-L", "hive", "-f", conf_path, "new-session"), stdout="@0\n"
        )
        ensure_session()
        assert (
            fake_proc.count("tmux", "-L", "hive", "-f", conf_path, "new-session") == 1
        )

    def test_ensure_session_is_a_noop_when_already_running(self, fake_proc):
        mux = TmuxMux()
        _cmd, ensure_session = session.prepare_tmux_attach(
            "s", mux=mux, hive="/opt/hive", settings=_settings()
        )
        conf_path = str(paths.layouts_dir() / "s" / "tmux.conf")
        fake_proc.script(
            ("tmux", "-L", "hive", "-f", conf_path, "has-session"), returncode=0
        )
        ensure_session()
        assert (
            fake_proc.count("tmux", "-L", "hive", "-f", conf_path, "new-session") == 0
        )

    def test_non_agent_layout_raises(self):
        mux = TmuxMux()
        settings = HiveSettings(zellij=ZellijConfig(layout="agent-16"))
        with pytest.raises(HiveError):
            session.prepare_tmux_attach(
                "s", mux=mux, hive="/opt/hive", settings=settings
            )


def test_start_calls_ensure_session_before_execvpe():
    calls = []
    with patch("hive_cli.services.session.os.execvpe"):
        session.start(
            ["tmux", "attach-session", "-t", "s"],
            {},
            session="s",
            mux=None,
            restart=False,
            restart_delay=0,
            on_restart=lambda: None,
            on_stop=lambda: None,
            ensure_session=lambda: calls.append(1),
        )
    assert calls == [1]


def test_start_calls_ensure_session_each_restart_iteration():
    from hive_cli.services.restart import RestartFloor

    calls: list[int] = []
    restarts: list[int] = []

    def on_restart():
        restarts.append(1)
        if len(restarts) == 2:
            raise KeyboardInterrupt

    with patch("hive_cli.services.session.subprocess.run"):
        session.start(
            ["tmux", "attach-session", "-t", "s"],
            {},
            session="s",
            mux=None,
            restart=True,
            restart_delay=0,
            on_restart=on_restart,
            on_stop=lambda: None,
            restart_floor=RestartFloor(sleep=lambda s: None),
            ensure_session=lambda: calls.append(1),
        )
    assert calls == [1, 1]


# ---------------------------------------------------------------------------
# F3: on-demand tabs/panes, floating shell, control-plane toggle
# ---------------------------------------------------------------------------


def test_pane_hive_id_reexported_from_state_pane_state():
    """Full regex coverage now lives in tests/test_state_pane.py, next to
    where `pane_hive_id` itself lives (state/pane_state.py); this just
    proves `services.session` still has a working `_pane_hive_id` alias."""
    assert session._pane_hive_id("c2: Bohdan") == 2


def _pane(
    id_: str,
    tab_id: str,
    *,
    focused: bool = False,
    title: str = "",
    suspended: bool = False,
) -> PaneInfo:
    return PaneInfo(
        id=id_,
        tab_id=tab_id,
        title=title,
        command="",
        cwd="",
        focused=focused,
        exited=False,
        suspended=suspended,
    )


def _live(session_name: str, pane_id: str, hive_pane_id: int) -> PaneStateServer:
    return PaneStateServer(
        paths.pane_sock(session_name, pane_id),
        PaneState(session=session_name, pane_id=pane_id, hive_pane_id=hive_pane_id),
    )


@pytest.fixture
def hive_path():
    with patch(
        "hive_cli.services.session.paths.hive_executable", return_value="/opt/hive"
    ):
        yield "/opt/hive"


def test_new_agent_pane_splits_when_room(hive_path):
    mux = FakeMux(session="s", panes=[_pane("3", "t1")])
    with _live("s", "3", 1):
        pane_id = session.new_agent_pane(mux=mux, settings=HiveSettings())

    calls = mux.named("new_pane")
    assert len(calls) == 1
    _name, args, kwargs = calls[0]
    argv = args[0]
    assert argv[:6] == (
        "/usr/bin/env",
        "HIVE_PANE_ID=2",
        "HIVE_PANE_LABEL=Bohdan",
        "/opt/hive",
        "run",
        "--restart",
    )
    assert kwargs["direction"] == "auto"
    assert kwargs["tab_id"] == "t1"
    # `name` gives the split pane its `cN: label` title at creation, so a
    # concurrent `new_agent_pane` call (a rapid-fire "new pane" keypress)
    # racing right behind it sees this pane in `_taken_pane_ids` immediately
    # instead of only once this pane's own `hive run` finishes booting and
    # renames it -- closing the window that let two calls hand out the same
    # number and label (the reused-names bug).
    assert kwargs["name"] == "c2: Bohdan"
    assert pane_id


def test_new_agent_pane_falls_back_to_label_pool_once_pane_labels_run_out(hive_path):
    """Beyond the configured `pane_labels`, a name still comes from
    `pane_label_pool` instead of the bare `cN` fallback -- the "ran out of
    names" bug: with only one configured label, pane 2 used to get no label
    (and no title match for the next call to recognize it) at all."""
    mux = FakeMux(session="s", panes=[_pane("3", "t1")])
    with _live("s", "3", 1):
        session.new_agent_pane(
            mux=mux,
            settings=HiveSettings(
                zellij=ZellijConfig(
                    pane_labels=["Anton"],
                    pane_label_pool=["Andriy", "Ethan"],
                )
            ),
        )

    argv = mux.named("new_pane")[0][1][0]
    label = argv[2].removeprefix("HIVE_PANE_LABEL=")
    assert label in ("Andriy", "Ethan")
    assert mux.named("new_pane")[0][2]["name"] == f"c2: {label}"


def test_new_agent_pane_pool_label_excludes_labels_already_taken(hive_path):
    """The random pick avoids any name a pane already carries -- whether via
    a live socket or a title-only pending pane elsewhere in the session, not
    just an index match in `pane_labels` -- so it never hands out a name
    that's already on screen. Pane "5" sits in a different tab (`t2`) so it
    plays no part in the same-tab idle-reuse check, only in what counts as
    a taken id/label session-wide."""
    mux = FakeMux(
        session="s",
        panes=[_pane("3", "t1"), _pane("5", "t2", title="c2: Ethan")],
    )
    with _live("s", "3", 1):
        session.new_agent_pane(
            mux=mux,
            settings=HiveSettings(
                zellij=ZellijConfig(
                    pane_labels=["Anton"],
                    pane_label_pool=["Ethan", "Andriy"],
                )
            ),
        )

    argv = mux.named("new_pane")[0][1][0]
    assert "HIVE_PANE_ID=3" in argv
    assert "HIVE_PANE_LABEL=Andriy" in argv
    assert "HIVE_PANE_LABEL=Ethan" not in argv


def test_new_agent_pane_never_opens_new_tab_when_target_tab_exists(hive_path):
    """The core of G4: no count, however high, spills to a new tab."""
    panes = [_pane(str(i), "t1", title=f"c{i}: X") for i in range(3, 9)]  # 6 agents
    mux = FakeMux(session="s", panes=panes)
    with contextlib.ExitStack() as stack:
        for i, p in enumerate(panes, start=1):
            stack.enter_context(_live("s", p.id, i))
        session.new_agent_pane(mux=mux, settings=HiveSettings())

    assert mux.named("new_tab") == []
    assert len(mux.named("new_pane")) == 1


def test_new_agent_pane_opens_fresh_tab_only_with_no_current_tab(hive_path):
    """An edge case, not an overflow case: nothing to split into at all, so
    a fresh one-pane agents tab is the only thing left to do."""
    mux = FakeMux(session="s", panes=[])
    mux.current_tab_id = lambda: None
    session.new_agent_pane(mux=mux, settings=HiveSettings())

    assert mux.named("new_pane") == []
    calls = mux.named("new_tab")
    assert len(calls) == 1
    spec = calls[0][1][0]
    assert spec.name == "agents"
    assert len(spec.panes) == 1
    assert spec.panes[0].suspended is False


def test_new_agent_pane_reuses_idle_suspended_pane(hive_path):
    """A never-started pane (c2, e.g. from `hive pane hold`) has no live
    hive socket yet -- only its layout-assigned title identifies it. Pressing
    "New agent" with that idle slot sitting there should resume it in place,
    not duplicate it (the pre-fix bug: a new pane split in and handed c2's
    own HIVE_PANE_ID again) -- and not just focus it either: `resume_pane`
    (the Enter keystroke that starts its pending command) must follow the
    focus, so the slot this hands back is actually running, not merely in
    view."""
    mux = FakeMux(
        session="s",
        panes=[
            _pane("3", "t1", title="c1: Anton"),
            _pane("4", "t1", title="c2: Bohdan", suspended=True),
        ],
    )
    with _live("s", "3", 1):
        pane_id = session.new_agent_pane(mux=mux, settings=HiveSettings())

    assert mux.named("new_pane") == []
    assert mux.named("new_tab") == []
    assert mux.named("focus_pane") == [("focus_pane", ("4",), {})]
    assert mux.named("resume_pane") == [("resume_pane", ("4",), {})]
    assert mux.calls.index(mux.named("focus_pane")[0]) < mux.calls.index(
        mux.named("resume_pane")[0]
    )
    assert pane_id == "4"


def test_new_agent_pane_prefers_named_idle_pane(hive_path):
    """Two idle slots in the same tab; `prefer_pane_id` picks the second,
    not the first-found (G1: the control plane's `n` names exactly the row
    the user selected)."""
    mux = FakeMux(
        session="s",
        panes=[
            _pane("4", "t1", title="c1: Anton", suspended=True),
            _pane("5", "t1", title="c2: Bohdan", suspended=True),
        ],
    )
    pane_id = session.new_agent_pane(
        mux=mux,
        prefer_pane_id="5",
        settings=HiveSettings(),
    )
    assert pane_id == "5"
    assert mux.named("focus_pane") == [("focus_pane", ("5",), {})]
    assert mux.named("resume_pane") == [("resume_pane", ("5",), {})]


def test_new_agent_pane_prefer_falls_back_when_not_idle(hive_path):
    """`prefer_pane_id` naming a pane that isn't idle (or not in `existing`
    at all) doesn't break anything -- falls back to first-idle-found."""
    mux = FakeMux(
        session="s", panes=[_pane("4", "t1", title="c1: Anton", suspended=True)]
    )
    pane_id = session.new_agent_pane(
        mux=mux,
        prefer_pane_id="does-not-exist",
        settings=HiveSettings(),
    )
    assert pane_id == "4"
    assert mux.named("resume_pane") == [("resume_pane", ("4",), {})]


def test_new_agent_pane_still_reuses_idle_slot_from_hold(hive_path):
    """`agents_tab` no longer creates idle slots, but `hive pane hold` still
    does -- the reuse path stays live for that."""
    mux = FakeMux(
        session="s",
        panes=[_pane("3", "t1", title="hold: c4: Bohdan", suspended=True)],
    )
    pane_id = session.new_agent_pane(mux=mux, settings=HiveSettings())
    assert pane_id == "3"
    assert mux.named("new_pane") == []
    assert mux.named("new_tab") == []


@pytest.mark.parametrize(
    ("control_plane", "direction"),
    [("tab", "auto"), ("none", "auto"), ("right", "right"), ("bottom", "right")],
)
def test_new_agent_pane_direction_follows_control_plane(
    hive_path, control_plane, direction
):
    """Count-driven agents tabs (control_plane tab/none) defer placement to
    Zellij's auto_layout -- a directional split marks the layout dirty and
    switches it off. right/bottom have no such presets and keep the split."""
    mux = FakeMux(session="s", panes=[_pane("3", "t1")])
    settings = HiveSettings(zellij=ZellijConfig(control_plane=control_plane))
    with _live("s", "3", 1):
        session.new_agent_pane(mux=mux, settings=settings)
    call = mux.named("new_pane")[0]
    assert call[2]["direction"] == direction
    assert "stacked" not in call[2]


def test_new_agent_pane_no_focus_skips_reuse_focus_call(hive_path):
    mux = FakeMux(
        session="s",
        panes=[
            _pane("3", "t1", title="c1: Anton"),
            _pane("4", "t1", title="c2: Bohdan", suspended=True),
        ],
    )
    with _live("s", "3", 1):
        pane_id = session.new_agent_pane(
            mux=mux,
            focus=False,
            settings=HiveSettings(),
        )

    assert mux.named("focus_pane") == []
    assert pane_id == "4"


def test_new_agent_pane_override_ignores_idle_pane_and_splits_a_fresh_one(hive_path):
    """An idle slot's command is fixed at layout time (no `-a`/`-p`/`-w`), so
    an explicit override must never be satisfied by silently resuming it."""
    mux = FakeMux(
        session="s",
        panes=[
            _pane("3", "t1", title="c1: Anton"),
            _pane("4", "t1", title="c2: Bohdan", suspended=True),
        ],
    )
    with _live("s", "3", 1):
        session.new_agent_pane(mux=mux, agent="codex", settings=HiveSettings())

    assert mux.named("resume_pane") == []
    assert mux.named("new_tab") == []
    calls = mux.named("new_pane")
    assert len(calls) == 1
    assert list(calls[0][1][0][-2:]) == ["-a", "codex"]


def test_new_agent_pane_splits_next_to_last_agent_not_focused_control_pane(hive_path):
    """The control-plane "hive" pane is where the "New agent" keypress
    physically originates, so it's Zellij's currently-active pane in the tab
    -- `new-pane --direction right` splits *that*, landing the new pane after
    "hive" instead of after the other agent pane, unless something first
    moves focus back onto an actual agent pane."""
    mux = FakeMux(
        session="s",
        panes=[
            _pane("3", "t1", title="c1: Anton"),
            _pane("9", "t1", title="hive", focused=True),
        ],
    )
    with _live("s", "3", 1):
        session.new_agent_pane(mux=mux, settings=HiveSettings())

    focus_calls = mux.named("focus_pane")
    new_pane_calls = mux.named("new_pane")
    assert focus_calls == [("focus_pane", ("3",), {})]
    assert len(new_pane_calls) == 1
    # the split call itself happens after the refocus onto the agent pane
    assert mux.calls.index(focus_calls[0]) < mux.calls.index(new_pane_calls[0])


def test_new_agent_pane_always_focuses_an_agent_pane_before_splitting(hive_path):
    """list-panes' `focused` is per-tab and tiled-only, so it names the agent
    pane even when the floating runner pane the hotkey opens holds real
    focus. Zellij drops a `new-pane --direction right` issued in that state
    (it still prints an id), so the focus call must happen anyway -- on the
    agent pane the user was on, so the split lands next to it."""
    mux = FakeMux(
        session="s",
        panes=[
            _pane("3", "t1", title="c1: Anton"),
            _pane("4", "t1", title="c2: Bohdan", focused=True),
            _pane("5", "t1", title="c3: Chris"),
        ],
    )
    with _live("s", "3", 1), _live("s", "4", 2), _live("s", "5", 3):
        session.new_agent_pane(mux=mux, settings=HiveSettings())

    focus_calls = mux.named("focus_pane")
    assert focus_calls == [("focus_pane", ("4",), {})]
    new_pane_call = mux.named("new_pane")[0]
    assert mux.calls.index(focus_calls[0]) < mux.calls.index(new_pane_call)


def test_new_agent_pane_passes_agent_profile_branch(hive_path):
    mux = FakeMux(session="s", panes=[_pane("3", "t1")])
    with _live("s", "3", 1):
        session.new_agent_pane(
            mux=mux,
            agent="codex",
            profile="work",
            branch="feat",
            settings=HiveSettings(),
        )

    argv = mux.named("new_pane")[0][1][0]
    assert list(argv[-6:]) == ["-a", "codex", "-p", "work", "-w", "feat"]


def test_open_tab_bundled_and_user(hive_path):
    from hive_cli.config.schema import PaneConfig, TabConfig

    mux = FakeMux(session="s")
    session.open_tab("git", mux=mux)
    assert mux.named("new_tab")[0][1][0].name == "git"

    custom = HiveSettings(
        tabs={"custom": TabConfig(panes=[PaneConfig(name="x", command="true")])}
    )
    with patch("hive_cli.services.session.get_settings", return_value=custom):
        session.open_tab("custom", mux=mux)
    assert mux.named("new_tab")[1][1][0].name == "custom"


def test_open_tab_unknown_is_hive_error(hive_path):
    mux = FakeMux(session="s")
    with pytest.raises(HiveError):
        session.open_tab("does-not-exist", mux=mux)


def test_open_tab_agents_uses_next_free_pane_id(hive_path):
    mux = FakeMux(session="s", panes=[_pane("3", "t1")])
    with _live("s", "3", 1):
        session.open_tab("agents", mux=mux)

    spec = mux.named("new_tab")[0][1][0]
    assert spec.name == "agents"
    assert spec.panes[0].env[0] == ("HIVE_PANE_ID", "2")


def test_open_tab_agents_is_always_one_live_pane(hive_path):
    mux = FakeMux(session="s", panes=[_pane("3", "t1")])
    with _live("s", "3", 1):
        session.open_tab("agents", mux=mux)

    spec = mux.named("new_tab")[0][1][0]
    assert len(spec.panes) == 1
    assert spec.panes[0].suspended is False


def test_open_tab_agents_pool_label_excludes_labels_already_taken(hive_path):
    """Past `pane_labels`, the random pick avoids a name already on screen
    in another tab."""
    mux = FakeMux(session="s", panes=[_pane("5", "t2", title="c9: Ethan")])
    custom = HiveSettings(
        zellij=ZellijConfig(pane_labels=[], pane_label_pool=["Ethan", "Andriy"])
    )
    with patch("hive_cli.services.session.get_settings", return_value=custom):
        session.open_tab("agents", mux=mux)

    spec = mux.named("new_tab")[0][1][0]
    assert dict(spec.panes[0].env)["HIVE_PANE_LABEL"] == "Andriy"


def test_resolve_here_matrix(tmp_path):
    main_repo = (tmp_path / "main").resolve()
    main_repo.mkdir()
    wt = (tmp_path / "wt").resolve()
    wt.mkdir()
    outer = (tmp_path / "wt-parent").resolve()
    inner = outer / "wt-child"
    inner.mkdir(parents=True)
    worktrees = [
        WorktreeInfo(branch="feat", path=wt),
        WorktreeInfo(branch="outer", path=outer),
        WorktreeInfo(branch="inner", path=inner),
    ]

    assert session.resolve_here(wt, main_repo, worktrees) == wt
    assert session.resolve_here(wt / "sub", main_repo, worktrees) == wt
    assert session.resolve_here(main_repo / "sub", main_repo, worktrees) == main_repo
    assert session.resolve_here(inner / "deep", main_repo, worktrees) == inner
    outside = Path("/definitely-not-under-any-candidate-hive-test")
    assert session.resolve_here(outside, main_repo, worktrees) is None


def test_floating_shell_here_uses_popup(tmp_path, monkeypatch):
    main_repo = (tmp_path / "main").resolve()
    main_repo.mkdir()
    monkeypatch.chdir(main_repo)
    expected_cwd = str(Path.cwd())

    with (
        patch("hive_cli.services.session.get_main_repo", return_value=main_repo),
        patch("hive_cli.services.session.list_worktrees", return_value=[]),
    ):
        mux = FakeMux(session="s")
        session.floating_shell(mux=mux, here=True)

    _name, args, kwargs = mux.named("popup")[0]
    assert kwargs["cwd"] == expected_cwd
    assert kwargs["name"] == "shell"


def test_floating_shell_here_outside_raises(tmp_path, monkeypatch):
    main_repo = (tmp_path / "main").resolve()
    main_repo.mkdir()
    outside = (tmp_path / "outside").resolve()
    outside.mkdir()
    monkeypatch.chdir(outside)

    with (
        patch("hive_cli.services.session.get_main_repo", return_value=main_repo),
        patch("hive_cli.services.session.list_worktrees", return_value=[]),
    ):
        mux = FakeMux(session="s")
        with pytest.raises(HiveError):
            session.floating_shell(mux=mux, here=True)


def test_toggle_control_plane_focuses_existing():
    with PaneStateServer(paths.control_sock("s"), PaneState(session="s", pane_id="9")):
        mux = FakeMux(session="s")
        assert session.toggle_control_plane(mux=mux, session="s") is True
    assert mux.named("focus_pane") == [("focus_pane", ("9",), {})]


def test_toggle_control_plane_when_absent_returns_false():
    mux = FakeMux(session="s")
    assert session.toggle_control_plane(mux=mux, session="s") is False
    assert mux.named("focus_pane") == []


def test_hold_waits_then_execs():
    prompts: list[str] = []
    waited: list[int] = []
    execs: list[tuple[str, list[str]]] = []

    code = session.hold(
        ["/opt/hive", "run"],
        prompt=prompts.append,
        wait=lambda: waited.append(1),
        exec_=lambda prog, argv: execs.append((prog, argv)),
    )

    assert code == 0
    assert waited == [1]
    assert execs == [("/opt/hive", ["/opt/hive", "run"])]
    assert prompts == ["[hive] press Enter to start: /opt/hive run"]
