"""Golden tests for hive_cli.mux.tmux.conf: KeybindSpec -> tmux.conf text."""

from __future__ import annotations

import pytest

from hive_cli.config.schema import KeybindsConfig
from hive_cli.core.errors import HiveError
from hive_cli.layout.keybinds import keybind_spec
from hive_cli.layout.model import SessionSpec
from hive_cli.mux.tmux.conf import render_conf, tmux_key

GOLDEN = """\
# generated by hive — do not edit
set -g mouse on
set -g remain-on-exit off
set -g set-titles on
set -g status-left "#S "
set -g window-status-format "#I:#W"
set -g window-status-current-format "#[bold]#I:#W"
bind -n M-n display-popup -E -d "#{pane_current_path}" -- /opt/hive pane new
bind -n M-A display-popup -E -d "#{pane_current_path}" -- /opt/hive tab agents
bind -n M-S display-popup -E -d "#{pane_current_path}" -T shell -- /opt/hive wt exec --here -- /bin/zsh
bind -n M-m display-popup -E -w 80% -h 80% -T hive -- /opt/hive status --toggle
bind -n M-W display-popup -E -d "#{pane_current_path}" -T shell -- /opt/hive wt exec --worktree - -- /bin/zsh
"""  # noqa: E501


@pytest.mark.parametrize(
    ("zellij_key", "expected"),
    [
        ("Alt a", "M-a"),
        ("Alt Shift a", "M-A"),
        ("Ctrl a", "C-a"),
        ("Alt Shift s", "M-S"),
        ("Alt Shift w", "M-W"),
    ],
)
def test_tmux_key_table(zellij_key, expected):
    assert tmux_key(zellij_key) == expected


def test_tmux_key_unsupported_modifier_raises():
    with pytest.raises(HiveError):
        tmux_key("Super a")


def test_render_conf_golden():
    keybinds = keybind_spec(KeybindsConfig(), hive="/opt/hive", shell="/bin/zsh")
    spec = SessionSpec(name="s", tabs=(), keybinds=keybinds)
    assert render_conf(spec, hive="/opt/hive") == GOLDEN


def test_disabled_keybinds_render_no_bind_lines():
    keybinds = keybind_spec(
        KeybindsConfig(enabled=False), hive="/opt/hive", shell="/bin/zsh"
    )
    spec = SessionSpec(name="s", tabs=(), keybinds=keybinds)
    out = render_conf(spec, hive="/opt/hive")
    assert "bind -n" not in out
    assert out.startswith("# generated by hive — do not edit\n")
