"""Tests for hive_cli.services.session: stale pane-socket cleanup on start,
attach_argv()'s layout resolution (F2: renders "agent" per session), and the
F3 on-demand tabs/panes/floating-shell/control-plane-toggle functions."""

from __future__ import annotations

from pathlib import Path
from unittest.mock import patch

import pytest
from fakes import FakeMux

from hive_cli.config.schema import ZellijConfig
from hive_cli.config.settings import HiveSettings
from hive_cli.core import paths
from hive_cli.core.errors import HiveError
from hive_cli.git.worktree import WorktreeInfo
from hive_cli.mux.base import PaneInfo
from hive_cli.mux.tmux.backend import TmuxMux
from hive_cli.services import session
from hive_cli.state.pane_state import PaneState
from hive_cli.state.server import PaneStateServer


def _start(mux, name):
    with patch("hive_cli.services.session.os.execvpe") as execvpe:
        session.start(
            ["zellij", "attach", "--create", name],
            {},
            session=name,
            mux=mux,
            restart=False,
            restart_delay=0,
            on_restart=lambda: None,
            on_stop=lambda: None,
        )
    execvpe.assert_called_once()


def test_session_start_removes_stale_sock_dir():
    stale = paths.session_sock_dir("s")
    stale.mkdir(parents=True)
    (stale / "3.sock").write_text("")
    mux = FakeMux(session="other")  # "s" is not running

    _start(mux, "s")

    assert not stale.exists()
    assert mux.named("session_exists") == [("session_exists", ("s",), {})]


def test_session_start_keeps_live_session_dir():
    live = paths.session_sock_dir("s")
    live.mkdir(parents=True)
    (live / "3.sock").write_text("")

    _start(FakeMux(session="s"), "s")

    assert (live / "3.sock").exists()


def test_session_start_without_mux_skips_cleanup():
    stale = paths.session_sock_dir("s")
    stale.mkdir(parents=True)

    _start(None, "s")

    assert stale.exists()


def test_clean_stale_sock_dir_tolerates_missing_dir():
    session.clean_stale_sock_dir(FakeMux(session="other"), "never-created")


def test_restart_loop_sleeps_after_fast_exits():
    from hive_cli.services.restart import RestartFloor

    class Clock:
        now = 1000.0

        def __call__(self):
            return self.now

    clock = Clock()
    slept: list[float] = []
    restarts: list[int] = []
    stops: list[int] = []

    def on_restart():
        restarts.append(1)
        if len(restarts) == 2:
            raise KeyboardInterrupt

    def fake_run(cmd, env):
        clock.now += 0.1

    with patch("hive_cli.services.session.subprocess.run", side_effect=fake_run) as run:
        session.start(
            ["zellij", "attach", "--create", "s"],
            {},
            session="s",
            mux=None,
            restart=True,
            restart_delay=0,
            on_restart=on_restart,
            on_stop=lambda: stops.append(1),
            restart_floor=RestartFloor(sleep=slept.append, clock=clock),
        )

    assert run.call_count == 2
    assert slept == [1] and stops == [1]


def _settings() -> HiveSettings:
    return HiveSettings(zellij=ZellijConfig())


class TestAttachArgv:
    def test_start_renders_and_attaches(self):
        mux = FakeMux(session="s")
        cmd = session.attach_argv(
            "agent", "s", mux=mux, hive="/opt/hive", settings=_settings()
        )
        rendered = paths.layouts_dir() / "s" / "session.kdl"
        assert rendered.is_file()
        assert rendered.read_text().startswith("layout {")
        assert cmd == ["fake-attach", "s", str(rendered)]

    def test_start_legacy_layout(self):
        mux = FakeMux(session="s")
        cmd = session.attach_argv(
            "agent-16", "s", mux=mux, hive="/opt/hive", settings=_settings()
        )
        assert cmd[0] == "fake-attach"
        assert cmd[1] == "s"
        assert cmd[2].endswith("bundled/agent-16.kdl")

    def test_resolve_layout_path_none(self):
        mux = FakeMux(session="s")
        cmd = session.attach_argv(
            None, "s", mux=mux, hive="/opt/hive", settings=_settings()
        )
        assert cmd == ["fake-attach", "s", ""]


class TestPrepareTmuxAttach:
    def test_renders_conf_and_returns_attach_argv(self, fake_proc):
        mux = TmuxMux()
        cmd, ensure_session = session.prepare_tmux_attach(
            "s", mux=mux, hive="/opt/hive", settings=_settings()
        )
        del ensure_session
        conf_path = paths.layouts_dir() / "s" / "tmux.conf"
        assert conf_path.is_file()
        assert conf_path.read_text().startswith("# generated by hive")
        assert cmd == [
            "tmux",
            "-L",
            "hive",
            "-f",
            str(conf_path),
            "attach-session",
            "-t",
            "s",
        ]

    def test_ensure_session_bootstraps_when_absent(self, fake_proc):
        mux = TmuxMux()
        _cmd, ensure_session = session.prepare_tmux_attach(
            "s", mux=mux, hive="/opt/hive", settings=_settings()
        )
        conf_path = str(paths.layouts_dir() / "s" / "tmux.conf")
        fake_proc.script(
            ("tmux", "-L", "hive", "-f", conf_path, "has-session"), returncode=1
        )
        fake_proc.script(
            ("tmux", "-L", "hive", "-f", conf_path, "new-session"), stdout="@0\n"
        )
        ensure_session()
        assert (
            fake_proc.count("tmux", "-L", "hive", "-f", conf_path, "new-session") == 1
        )

    def test_ensure_session_is_a_noop_when_already_running(self, fake_proc):
        mux = TmuxMux()
        _cmd, ensure_session = session.prepare_tmux_attach(
            "s", mux=mux, hive="/opt/hive", settings=_settings()
        )
        conf_path = str(paths.layouts_dir() / "s" / "tmux.conf")
        fake_proc.script(
            ("tmux", "-L", "hive", "-f", conf_path, "has-session"), returncode=0
        )
        ensure_session()
        assert (
            fake_proc.count("tmux", "-L", "hive", "-f", conf_path, "new-session") == 0
        )

    def test_non_agent_layout_raises(self):
        mux = TmuxMux()
        settings = HiveSettings(zellij=ZellijConfig(layout="agent-16"))
        with pytest.raises(HiveError):
            session.prepare_tmux_attach(
                "s", mux=mux, hive="/opt/hive", settings=settings
            )


def test_start_calls_ensure_session_before_execvpe():
    calls = []
    with patch("hive_cli.services.session.os.execvpe"):
        session.start(
            ["tmux", "attach-session", "-t", "s"],
            {},
            session="s",
            mux=None,
            restart=False,
            restart_delay=0,
            on_restart=lambda: None,
            on_stop=lambda: None,
            ensure_session=lambda: calls.append(1),
        )
    assert calls == [1]


def test_start_calls_ensure_session_each_restart_iteration():
    from hive_cli.services.restart import RestartFloor

    calls: list[int] = []
    restarts: list[int] = []

    def on_restart():
        restarts.append(1)
        if len(restarts) == 2:
            raise KeyboardInterrupt

    with patch("hive_cli.services.session.subprocess.run"):
        session.start(
            ["tmux", "attach-session", "-t", "s"],
            {},
            session="s",
            mux=None,
            restart=True,
            restart_delay=0,
            on_restart=on_restart,
            on_stop=lambda: None,
            restart_floor=RestartFloor(sleep=lambda s: None),
            ensure_session=lambda: calls.append(1),
        )
    assert calls == [1, 1]


# ---------------------------------------------------------------------------
# F3: on-demand tabs/panes, floating shell, control-plane toggle
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("title", "expected"),
    [
        ("c2: Bohdan", 2),
        ("c2: Bohdan [claude]", 2),
        ("c12", 12),
        ("hold: c2: Bohdan", 2),  # tmux's suspended-pane title (commands/pane.py:hold)
        ("hold: c2", 2),
        ("hold: hive run --restart", None),  # a hold pane with no HIVE_PANE_ID env
        ("hive", None),
        ("", None),
    ],
)
def test_pane_hive_id_parses_zellij_and_tmux_titles(title, expected):
    assert session._pane_hive_id(title) == expected


def _pane(
    id_: str,
    tab_id: str,
    *,
    focused: bool = False,
    title: str = "",
    suspended: bool = False,
) -> PaneInfo:
    return PaneInfo(
        id=id_,
        tab_id=tab_id,
        title=title,
        command="",
        cwd="",
        focused=focused,
        exited=False,
        suspended=suspended,
    )


def _live(session_name: str, pane_id: str, hive_pane_id: int) -> PaneStateServer:
    return PaneStateServer(
        paths.pane_sock(session_name, pane_id),
        PaneState(session=session_name, pane_id=pane_id, hive_pane_id=hive_pane_id),
    )


@pytest.fixture
def hive_path():
    with patch(
        "hive_cli.services.session.paths.hive_executable", return_value="/opt/hive"
    ):
        yield "/opt/hive"


def test_new_agent_pane_splits_when_room(hive_path):
    mux = FakeMux(session="s", panes=[_pane("3", "t1")])
    with _live("s", "3", 1):
        pane_id = session.new_agent_pane(
            mux=mux, settings=HiveSettings(zellij=ZellijConfig(agents_per_tab=2))
        )

    calls = mux.named("new_pane")
    assert len(calls) == 1
    _name, args, kwargs = calls[0]
    argv = args[0]
    assert argv[:6] == (
        "/usr/bin/env",
        "HIVE_PANE_ID=2",
        "HIVE_PANE_LABEL=Bohdan",
        "/opt/hive",
        "run",
        "--restart",
    )
    assert kwargs["direction"] == "right"
    assert kwargs["tab_id"] == "t1"
    assert pane_id


def test_new_agent_pane_opens_tab_when_full(hive_path):
    mux = FakeMux(session="s", panes=[_pane("3", "t1"), _pane("4", "t1")])
    with _live("s", "3", 1), _live("s", "4", 2):
        session.new_agent_pane(
            mux=mux, settings=HiveSettings(zellij=ZellijConfig(agents_per_tab=2))
        )

    assert mux.named("new_pane") == []
    calls = mux.named("new_tab")
    assert len(calls) == 1
    spec = calls[0][1][0]
    assert spec.name == "agents"
    assert len(spec.panes) == 1
    assert spec.panes[0].env == (("HIVE_PANE_ID", "3"), ("HIVE_PANE_LABEL", "Chris"))


def test_new_agent_pane_reuses_idle_suspended_pane(hive_path):
    """A `start_suspended` pane from the initial agents_tab (c2) has no live
    hive socket yet -- only its layout-assigned title identifies it. Pressing
    "New agent" with that idle slot sitting there should focus/start it, not
    duplicate it (the pre-fix bug: a 3rd pane split into an already-full
    2-agent tab, handed c2's own HIVE_PANE_ID again)."""
    mux = FakeMux(
        session="s",
        panes=[
            _pane("3", "t1", title="c1: Anton"),
            _pane("4", "t1", title="c2: Bohdan", suspended=True),
        ],
    )
    with _live("s", "3", 1):
        pane_id = session.new_agent_pane(
            mux=mux, settings=HiveSettings(zellij=ZellijConfig(agents_per_tab=2))
        )

    assert mux.named("new_pane") == []
    assert mux.named("new_tab") == []
    assert mux.named("focus_pane") == [("focus_pane", ("4",), {})]
    assert pane_id == "4"


def test_new_agent_pane_no_focus_skips_reuse_focus_call(hive_path):
    mux = FakeMux(
        session="s",
        panes=[
            _pane("3", "t1", title="c1: Anton"),
            _pane("4", "t1", title="c2: Bohdan", suspended=True),
        ],
    )
    with _live("s", "3", 1):
        pane_id = session.new_agent_pane(
            mux=mux,
            focus=False,
            settings=HiveSettings(zellij=ZellijConfig(agents_per_tab=2)),
        )

    assert mux.named("focus_pane") == []
    assert pane_id == "4"


def test_new_agent_pane_override_ignores_idle_pane_and_opens_tab_when_full(hive_path):
    """An idle slot's command is fixed at layout time (no `-a`/`-p`/`-w`), so
    an explicit override must never be satisfied by silently resuming it."""
    mux = FakeMux(
        session="s",
        panes=[
            _pane("3", "t1", title="c1: Anton"),
            _pane("4", "t1", title="c2: Bohdan", suspended=True),
        ],
    )
    with _live("s", "3", 1):
        session.new_agent_pane(
            mux=mux,
            agent="codex",
            settings=HiveSettings(zellij=ZellijConfig(agents_per_tab=2)),
        )

    assert mux.named("new_pane") == []
    calls = mux.named("new_tab")
    assert len(calls) == 1
    spec = calls[0][1][0]
    assert spec.panes[0].env == (("HIVE_PANE_ID", "3"), ("HIVE_PANE_LABEL", "Chris"))


def test_new_agent_pane_splits_next_to_last_agent_not_focused_control_pane(hive_path):
    """The control-plane "hive" pane is where the "New agent" keypress
    physically originates, so it's Zellij's currently-active pane in the tab
    -- `new-pane --direction right` splits *that*, landing the new pane after
    "hive" instead of after the other agent pane, unless something first
    moves focus back onto an actual agent pane."""
    mux = FakeMux(
        session="s",
        panes=[
            _pane("3", "t1", title="c1: Anton"),
            _pane("9", "t1", title="hive", focused=True),
        ],
    )
    with _live("s", "3", 1):
        session.new_agent_pane(
            mux=mux, settings=HiveSettings(zellij=ZellijConfig(agents_per_tab=2))
        )

    focus_calls = mux.named("focus_pane")
    new_pane_calls = mux.named("new_pane")
    assert focus_calls == [("focus_pane", ("3",), {})]
    assert len(new_pane_calls) == 1
    # the split call itself happens after the refocus onto the agent pane
    assert mux.calls.index(focus_calls[0]) < mux.calls.index(new_pane_calls[0])


def test_new_agent_pane_no_refocus_when_already_on_an_agent_pane(hive_path):
    mux = FakeMux(
        session="s", panes=[_pane("3", "t1", title="c1: Anton", focused=True)]
    )
    with _live("s", "3", 1):
        session.new_agent_pane(
            mux=mux, settings=HiveSettings(zellij=ZellijConfig(agents_per_tab=2))
        )

    assert mux.named("focus_pane") == []


def test_new_agent_pane_passes_agent_profile_branch(hive_path):
    mux = FakeMux(session="s", panes=[_pane("3", "t1")])
    with _live("s", "3", 1):
        session.new_agent_pane(
            mux=mux,
            agent="codex",
            profile="work",
            branch="feat",
            settings=HiveSettings(zellij=ZellijConfig(agents_per_tab=2)),
        )

    argv = mux.named("new_pane")[0][1][0]
    assert list(argv[-6:]) == ["-a", "codex", "-p", "work", "-w", "feat"]


def test_open_tab_bundled_and_user(hive_path):
    from hive_cli.config.schema import PaneConfig, TabConfig

    mux = FakeMux(session="s")
    session.open_tab("git", mux=mux)
    assert mux.named("new_tab")[0][1][0].name == "git"

    custom = HiveSettings(
        tabs={"custom": TabConfig(panes=[PaneConfig(name="x", command="true")])}
    )
    with patch("hive_cli.services.session.get_settings", return_value=custom):
        session.open_tab("custom", mux=mux)
    assert mux.named("new_tab")[1][1][0].name == "custom"


def test_open_tab_unknown_is_hive_error(hive_path):
    mux = FakeMux(session="s")
    with pytest.raises(HiveError):
        session.open_tab("does-not-exist", mux=mux)


def test_open_tab_agents_uses_next_free_pane_id(hive_path):
    mux = FakeMux(session="s", panes=[_pane("3", "t1")])
    with _live("s", "3", 1):
        session.open_tab("agents", mux=mux)

    spec = mux.named("new_tab")[0][1][0]
    assert spec.name == "agents"
    assert len(spec.panes) == HiveSettings().zellij.agents_per_tab
    assert spec.panes[0].env[0] == ("HIVE_PANE_ID", "2")


def test_resolve_here_matrix(tmp_path):
    main_repo = (tmp_path / "main").resolve()
    main_repo.mkdir()
    wt = (tmp_path / "wt").resolve()
    wt.mkdir()
    outer = (tmp_path / "wt-parent").resolve()
    inner = outer / "wt-child"
    inner.mkdir(parents=True)
    worktrees = [
        WorktreeInfo(branch="feat", path=wt),
        WorktreeInfo(branch="outer", path=outer),
        WorktreeInfo(branch="inner", path=inner),
    ]

    assert session.resolve_here(wt, main_repo, worktrees) == wt
    assert session.resolve_here(wt / "sub", main_repo, worktrees) == wt
    assert session.resolve_here(main_repo / "sub", main_repo, worktrees) == main_repo
    assert session.resolve_here(inner / "deep", main_repo, worktrees) == inner
    outside = Path("/definitely-not-under-any-candidate-hive-test")
    assert session.resolve_here(outside, main_repo, worktrees) is None


def test_floating_shell_here_uses_popup(tmp_path, monkeypatch):
    main_repo = (tmp_path / "main").resolve()
    main_repo.mkdir()
    monkeypatch.chdir(main_repo)
    expected_cwd = str(Path.cwd())

    with (
        patch("hive_cli.services.session.get_main_repo", return_value=main_repo),
        patch("hive_cli.services.session.list_worktrees", return_value=[]),
    ):
        mux = FakeMux(session="s")
        session.floating_shell(mux=mux, here=True)

    _name, args, kwargs = mux.named("popup")[0]
    assert kwargs["cwd"] == expected_cwd
    assert kwargs["name"] == "shell"


def test_floating_shell_here_outside_raises(tmp_path, monkeypatch):
    main_repo = (tmp_path / "main").resolve()
    main_repo.mkdir()
    outside = (tmp_path / "outside").resolve()
    outside.mkdir()
    monkeypatch.chdir(outside)

    with (
        patch("hive_cli.services.session.get_main_repo", return_value=main_repo),
        patch("hive_cli.services.session.list_worktrees", return_value=[]),
    ):
        mux = FakeMux(session="s")
        with pytest.raises(HiveError):
            session.floating_shell(mux=mux, here=True)


def test_toggle_control_plane_focuses_existing():
    with PaneStateServer(paths.control_sock("s"), PaneState(session="s", pane_id="9")):
        mux = FakeMux(session="s")
        assert session.toggle_control_plane(mux=mux, session="s") is True
    assert mux.named("focus_pane") == [("focus_pane", ("9",), {})]


def test_toggle_control_plane_when_absent_returns_false():
    mux = FakeMux(session="s")
    assert session.toggle_control_plane(mux=mux, session="s") is False
    assert mux.named("focus_pane") == []


def test_hold_waits_then_execs():
    prompts: list[str] = []
    waited: list[int] = []
    execs: list[tuple[str, list[str]]] = []

    code = session.hold(
        ["/opt/hive", "run"],
        prompt=prompts.append,
        wait=lambda: waited.append(1),
        exec_=lambda prog, argv: execs.append((prog, argv)),
    )

    assert code == 0
    assert waited == [1]
    assert execs == [("/opt/hive", ["/opt/hive", "run"])]
    assert prompts == ["[hive] press Enter to start: /opt/hive run"]
