"""Render `layout.model` to a private-server tmux.conf: static options, the
tab-bar format, and the F3 keybinds translated to tmux's `bind -n <key> ...`
syntax.

Golden-tested byte-for-byte (tests/test_mux_tmux_conf.py). This file is only
ever loaded via `tmux -L <server> -f <path>` on hive's own private server —
it never touches the user's `~/.tmux.conf` or `~/.config/tmux/tmux.conf`.
"""

from __future__ import annotations

import shlex

from ...core.errors import HiveError
from ...layout.model import SessionSpec

_HEADER = (
    "# generated by hive — do not edit",
    "set -g mouse on",
    "set -g remain-on-exit off",
    "set -g set-titles on",
    'set -g status-left "#S "',
    'set -g window-status-format "#I:#W"',
    'set -g window-status-current-format "#[bold]#I:#W"',
)

_MOD_PREFIX = {"Ctrl": "C-", "Alt": "M-"}


def tmux_key(zellij_key: str) -> str:
    """ "Alt a" -> "M-a"; "Alt Shift a" -> "M-A"; "Ctrl a" -> "C-a".

    Raises HiveError for a modifier tmux has no prefix for (e.g. "Super").
    """
    parts = zellij_key.split()
    if not parts:
        raise HiveError(f"invalid keybind: {zellij_key!r}")
    *mods, key = parts
    shift = "Shift" in mods
    prefixes: list[str] = []
    for mod in mods:
        if mod == "Shift":
            continue
        if mod not in _MOD_PREFIX:
            raise HiveError(f"unsupported keybind modifier {mod!r} in {zellij_key!r}")
        prefixes.append(_MOD_PREFIX[mod])
    return "".join(prefixes) + (key.upper() if shift else key.lower())


def _bind_line(key: str, argv: tuple[str, ...], opts: dict[str, str | bool]) -> str:
    tkey = tmux_key(key)
    if not opts.get("floating"):
        return f'bind -n {tkey} run-shell "{shlex.join(argv)}"'
    parts = [f"bind -n {tkey} display-popup"]
    if opts.get("close_on_exit"):
        parts.append("-E")
    width, height = opts.get("width"), opts.get("height")
    if not width and not height:
        # No fixed size => this popup is meant to feel "here": match Zellij's
        # Run panes, which always open in the calling pane's own cwd.
        parts.append('-d "#{pane_current_path}"')
    if width:
        parts.append(f"-w {width}")
    if height:
        parts.append(f"-h {height}")
    name = opts.get("name")
    if name:
        parts.append(f"-T {name}")
    parts.append("--")
    parts.append(" ".join(shlex.quote(str(a)) for a in argv))
    return " ".join(parts)


def render_conf(spec: SessionSpec, *, hive: str) -> str:
    """The rendered tmux.conf: static options + F3 keybinds (or none).

    `hive` is accepted for signature parity with `mux/zellij/kdl.render_session_file`
    (both are `Callable[[SessionSpec, str], str]`) but unused: the resolved
    hive path is already baked into `spec.keybinds`' argv by `layout/keybinds.py`.
    """
    del hive  # documented no-op: argv already carries the resolved hive path
    lines: list[str] = list(_HEADER)
    lines.extend(
        _bind_line(key, argv, opts) for key, argv, opts in spec.keybinds.bindings
    )
    return "\n".join(lines) + "\n"
