"""Git utilities for hive CLI."""

from .analysis import (
    HIVE_MANAGED_FILES,
    MergeSimulation,
    changed_files,
    commits_ahead_behind,
    fetch_branch,
    get_diff,
    has_delta,
    merge_changed_files,
    show_diff_with_delta,
    simulate_merge,
)
from .github import (
    GitHubIssue,
    GitHubIssueDetails,
    fetch_issue_details,
    fetch_issues,
    get_github_repo_info,
    get_issues_cache_path,
    load_cached_issues,
    save_cached_issues,
)
from .repo import get_current_worktree_branch, get_git_root, get_main_repo
from .status import (
    CommitInfo,
    GitStatusDetail,
    get_git_status_detail,
    get_recent_commits,
    last_commit_summary,
    upstream_ahead_behind,
)
from .worktree import (
    WorktreeInfo,
    create_worktree,
    delete_worktree,
    fetch_origin,
    get_all_branches,
    get_current_branch,
    get_default_branch,
    get_worktree_path,
    is_worktree_dirty,
    list_worktrees,
    worktree_exists,
)
from .worktree_paths import expand_path, get_worktrees_base, sanitize_branch_name

__all__ = [
    "CommitInfo",
    "GitHubIssue",
    "GitHubIssueDetails",
    "GitStatusDetail",
    "HIVE_MANAGED_FILES",
    "MergeSimulation",
    "WorktreeInfo",
    "changed_files",
    "commits_ahead_behind",
    "create_worktree",
    "delete_worktree",
    "expand_path",
    "fetch_branch",
    "fetch_issue_details",
    "fetch_issues",
    "fetch_origin",
    "get_all_branches",
    "get_current_branch",
    "get_current_worktree_branch",
    "get_default_branch",
    "get_diff",
    "get_git_root",
    "get_git_status_detail",
    "get_github_repo_info",
    "get_issues_cache_path",
    "get_main_repo",
    "get_recent_commits",
    "get_worktree_path",
    "get_worktrees_base",
    "has_delta",
    "is_worktree_dirty",
    "last_commit_summary",
    "list_worktrees",
    "load_cached_issues",
    "merge_changed_files",
    "sanitize_branch_name",
    "save_cached_issues",
    "show_diff_with_delta",
    "simulate_merge",
    "upstream_ahead_behind",
    "worktree_exists",
]
